We will start in Auth.js file as there are no dependencies for this file. Auth.js will have the three
following functions and we will be making use of HTML5's `localStorage` object.

----
export default {
    <1>
    logIn(auth) {
        console.log(`Auth:login: ${auth}`);
        if (auth) {
            localStorage.auth = JSON.stringify(auth);
        }
    },

    <2>
    logOut() {
        console.log(`Auth:logOut: ${localStorage.auth}`);
        delete localStorage.auth;
    },

    <3>
    loggedIn() {
        console.log(`Auth:loggedIn?: ${localStorage.auth ? 'true' : 'false'}`);
        return !!localStorage.auth;
    }
};
----

Our login function is fairly simple as it will take in an auth object and so long as its not null we
will convert it to a JSON string and store it in our `localStorage` at `localStorage.auth` for later
use.
[source, react]
----
<1>
logIn(auth) {
    if (auth) {
        localStorage.auth = JSON.stringify(auth);
    }
}
----

Logout is actually even simpler as it doesn't require any arguments or perform any checks. When logOut
is called we simply remove the data that is stored at `localStorage.auth`.
[source, react]
----
<2>
logOut() {
    delete localStorage.auth;
}
----

Finally it might be useful to be able to check if we are logged in. So in this case we return a simple
boolean of whether or not auth exists in `localStorage`.
[source, react]
----
<3>
loggedIn() {
    return !!localStorage.auth;
}
----

Now that we have our base of client side authentication in place lets move on.